$entry_color = rgb(251, 222, 255)
# BACKGROUND
background {
monitor =
path = ~/.config/hypr/Catppuccin/hyprlock/megumin.jpg
#color = $background
blur_passes = 1
contrast = 1
brightness = 0.8
vibrancy = 0.2
vibrancy_darkness = 0.2
 }

 # GENERAL
 general {
no_fade_in = true
no_fade_out = true
hide_cursor = false
grace = 0
disable_loading_bar = true
 }

# # INPUT FIELD
#
# # input-field {
# #     monitor =
# #     size = 250, 50
# #     outline_thickness = 2
# #     dots_size = 0.1
# #     dots_spacing = 0.3
# #     outer_color = rgba(908F9F55)
# #   inner_color = rgba(33333311)
# #   font_color = rgba(C6C5D6FF)
# #   # fade_on_empty = true
#     position = 0, 20
#     halign = center
#     valign = center
# }

input-field {
    monitor =
    size = 11%, 5%
    outline_thickness = 3
    dots_size = 0.2 
    dots_spacing = 0.35 
    dots_center = true
    outer_color =  rgb(26032f) rgb(ff8c00) -25deg
    inner_color =rgb(254, 244, 255)
    font_color = rgb(3, 2, 3)
    fade_on_empty = false
    rounding = -1
    check_color =  rgb(253, 198, 252);
    placeholder_text = <i><span font_family="DS Moster" foreground="##1e1e2e">Input Password...</span></i>
    hide_input = false
    position = 0, -50
    halign = center
    valign = center
}

# DATE
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = rgb(205, 214, 244)
  font_size = 22
  font_family = DS Moster
  position = 0, -400
  halign = center
  valign = center
}

# TIME
label {
  monitor = 
  text = cmd[update:1000] echo "$(date +"%-H:%M")"
  color = $entry_color 
  font_size = 95
  font_family = DS Moster
  position = 0, -320
  halign = center
  valign = center
}



# Profile Picture
image {
    monitor =
    path = ~/.config/hypr/aqua.jpg
    size = 200
    border_size = 10
    border_color = $entry_color 
    position = 0, 100
    halign = center
    valign = center
}

# Desktop Environment
# image {
#     monitor =
#     path = ~/.config/hypr/aqua.jpg
#     size = 75
#     border_size = 2
#     border_color =$entry_color 
#     position = -50, 50
#     halign = right
#     valign = bottom
# }

# CURRENT SONG
label {
    monitor =
    text = cmd[update:1000] echo "$(playerctl metadata --format '{{artist}} - {{title}}' 2>/dev/null)" 
    color = $entry_color 
    font_size = 16
    font_family = DS Moster
    position = 0, 50
    halign = center
    valign = bottom
}

label {
    monitor =
    text = cmd[update:1000] echo "$(whoami)"
    color =  $entry_color 
  font_size = 14
    font_family = DS Moster
    position = 0, -10
    halign = center
    valign = top
}

label {
    monitor =
    text = cmd[update:1000] echo "$(~/.config/scripts/battery_status.sh)"
    color = $entry_color 
    font_size = 17
    font_family = JetBrains Mono
    position = -90, -10
    halign = right
    valign = top
}

