local home = os.getenv("HOME")

hl.env("GDK_BACKEND", "wayland,x11,*")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORMTHEME", "gtk3")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_STYLE_OVERRIDE", "Catppuccin-Mocha")
hl.env("GTK_THEME", "catppuccin-mocha-maroon-standard+default")
hl.env("TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY", "1")
hl.env("SDL_VIDEODRIVER", "wayland")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("EDITOR", "nvim")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XCURSOR_THEME", "Catppuccin-Mocha-Maroon-Cursors")
hl.env("XCURSOR_SIZE", "24")
hl.env("FASTFETCH_LOGO_PATH", home .. "/.config/fastfetch/pngs/Witch2.png")
hl.env("LIVE_WALLPAPER_PATH", home .. "/Live_Wallpaper/witch/Witch.mp4")
