exec-once = [workspace 1 silent]firefox
exec-once = otd-daemon
exec-once = [workspace 1 silent]v2rayn
exec-once = waybar -c ~/.config/hypr/Catppuccin/waybar/config.jsonc -s ~/.config/hypr/Catppuccin/waybar/style.css
exec-once = Telegram -startintray
exec-once = mako -c ~/.config/hypr/Catppuccin/mako/config
exec-once = systemctl --user start hyprpolkitagent
exec-once = brightnessctl set 100%
exec-once = ~/.config/scripts/LiveWallpaper.sh
exec-once = ~/.config/scripts/bins/image_processor || notify-send  -i "/usr/share/icons/Tela-circle-black/scalable/apps/script-error.svg" --hint=int:transient:1 --expire-time=40000  --hint=string:x-canonical-private-synchronous:9999 -u critical "Error" "image_processor exited with error"
# exec-once = dbus-update-activation-environment --all
# exec-once = sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = gsettings set org.gnome.desktop.interface gtk-theme Catppuccin-Mocha-Maroon-Cursors
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'Catppuccin-Mocha-Maroon-Cursors'
exec-once = gsettings set org.gnome.desktop.interface icon-theme Tela-circle-black
exec-once = hyprctl setcursor Catppuccin-Mocha-Maroon-Cursors 24
