exec-once = [workspace 5 silent]hiddify
exec-once = [workspace 1 silent]firefox
exec-once = waybar -c ~/.config/hypr/Catppuccin/waybar/config.jsonc -s ~/.config/hypr/Catppuccin/waybar/style.css
exec-once = telegram-desktop -startintray
exec-once = mako -c ~/.config/hypr/Catppuccin/mako/config
exec-once = ~/.config/scripts/hwdec.sh
exec-once = ~/.config/scripts/LiveWallpaper.sh
exec-once = ~/.config/scripts/bins/image_processor
# exec-once = swaybg -i ~/Wallpapers/space.png
exec-once = dbus-update-activation-environment --all
exec-once = sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = gsettings set org.gnome.desktop.interface gtk-theme Catppuccin-Mocha-Maroon-Cursors
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'Catppuccin-Mocha-Maroon-Cursors'
exec-once = hyprctl setcursor Catppuccin-Mocha-Maroon-Cursors 24
