exec-once = [workspace 4 silent]hiddify
exec-once = waybar -c ~/.config/hypr/Ayanami_Ray/waybar/config.jsonc -s ~/.config/hypr/Ayanami_Ray/waybar/style.css
exec-once = telegram-desktop -startintray
exec-once = [workspace 1 silent]firefox
exec-once = brightnessctl set 100%
exec-once = mako -c ~/.config/hypr/Ayanami_Ray/mako/config
exec-once = mpvpaper -o "no-audio --hwdec=auto --loop" "*" ~/Live_Wallpaper/output1.mp4
# exec-once = ~/.config/scripts/LiveWallpaper.sh
exec-once = ~/.config/hypr/image_processorNearest1_
# exec-once = swaybg -i ~/Wallpapers/space.png
# exec-once = gsettings set org.gnome.desktop.interface gtk-theme Catppuccin-Mocha-Teal-Cursors
# exec-once = gsettings set org.gnome.desktop.interface icon-theme Catppuccin-Mocha-Alt2
exec-once = hyprctl setcursor Catppuccin-Mocha-Teal-Cursors 24
exec-once = dbus-update-activation-environment --all
exec-once = sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'Catppuccin-Mocha-Teal-Cursors'
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'catppuccin-mocha-teal-standard+default'
