source = /home/cybercat/.config/hypr/windowrules.conf
source = /home/cybercat/.config/hypr/Ayanami_Ray/base.conf
source = /home/cybercat/.config/hypr/Ayanami_Ray/binds.conf
source = /home/cybercat/.config/hypr/Ayanami_Ray/env.conf
source = /home/cybercat/.config/hypr/Ayanami_Ray/autostart.conf
source = /home/cybercat/.config/hypr/Ayanami_Ray/nvidia.conf
