#Telegram rules
windowrule    = float,^(org.telegram.desktop)$
windowrule    = size 100 700,^(org.telegram.desktop)$
windowrule    = opacity 0.92,^(org.telegram.desktop)$
windowrule    = pin,^(org.telegram.desktop)$
windowrule    = move 87.15% 34.835%,^(org.telegram.desktop)$


#NMWUI rules
windowrule    = stayfocused,(nmwui)$
windowrule    = float,^(nmwui)$
windowrule    = size 760 500,^(nmwui)$
windowrule    = pin,^(nmwui)$

#OTHER rules
windowrulev2  = opacity 0.89,class:^(kitty)$
windowrulev2  = opacity 0.96,class:^(firefox)$
windowrulev2  = opacity 0.96,class:^(Code)$ 
windowrulev2  = opacity 0.95,class:^(far2l)$


# BLUETOOTH rules
windowrule   = stayfocused,(bluetooth)$
windowrule   = float,^(bluetooth)$
windowrule   = size 1000 500,^(bluetooth)$
windowrule   = pin,^(bluetooth)$


#Firefox-Library rules
windowrulev2 = float, title:^(Library)$
windowrule   = size 30%, title:^(Library)$
windowrule   = move 50% 50%, title:^(Library)$
windowrule   = float, title:^(Library)$
windowrulev2 = opacity 0.82, title:^(Library)$


#Picture-In-Picture rules
windowrule   = float, title:^(Picture-in-Picture)$
windowrule   = size 40%, title:^(Picture-in-Picture)$
windowrule   = pin, title:^(Picture-in-Picture)$
windowrule   = move 60% 59%, title:^(Picture-in-Picture)$
windowrulev2 = opacity 1, title:^(Picture-in-Picture)
windowrule   = float, title:^(Sign)$


#YouTube rule
windowrulev2 = opacity 1.0 1.0, title:^(.*YouTube.*)$
windowrulev2 = opacity 1.0 override, fullscreen:1, title:^(.*YouTube.*)$

#VLC rules
windowrulev2 = opacity 1.0, title:^(vlc)

#Ranger rules
windowrulev2 = opacity 0.89,class:^(ranger)$

#PulseMixer Rule
windowrule   = stayfocused,(pulsemixer)$
windowrule   = float,^(pulsemixer)$
windowrule   = size 1000 500,^(pulsemixer)$
windowrule   = pin,^(pulsemixer)$
windowrulev2 = opacity 0.89, title:^(pulsemixer)$

#Animego

windowrulev2 = opacity 1.0 1.0, title:^(.*anime.*)$
windowrulev2 = opacity 1.0 override, fullscreen:1, title:^(.*anime.*)$
# windowrulev2 = opacity 1.0 override, fullscreen:1, title:^(*Этот*)$

windowrule   =  float,^(nemo)$

windowrulev2 =  float,^(kitty)$,title:^(cmus)$

windowrule   = float,^(Viewnior)$
windowrule   = size 800 450,^(Viewnior)$
windowrule   = center,^(Viewnior)$


windowrule   = size 900 600,^(lutris)$
windowrule   = float,^(lutris)$
windowrule   = center,^(lutris)$

#Rofi rules
windowrule   = float,^(Rofi)$
windowrulev2 = stayfocused,class:(Rofi)
windowrule   = pin,^(Rofi)$
windowrulev2 = opacity 0.96, class:(Rofi)$


#swayimg rules
windowrule   = float,^(swayimg)$
windowrule   = size 800 450,^(swayimg)$
windowrule   = center,^(swayimg)$

#hiddify rules
windowrule   = float,^(hiddify)$
windowrule   = size 450 800,^(hiddify)$
windowrule   = center,^(hiddify)$


