$entry_color = rgb(C2185B)
$clock_font_size = 111
# BACKGROUND
background {
monitor =
path = ~/.config/hypr/Ayanami_Ray/hyprlock/background.png
#color = $background
contrast = 1
brightness = 0.8
vibrancy = 0.2
vibrancy_darkness = 0.2
zindex = 1
 }

 # GENERAL
 general {
no_fade_in = true
no_fade_out = true
hide_cursor = true
grace = 0
disable_loading_bar = true
 }

background {
    monitor =
    path = ~/.config/hypr/Ayanami_Ray/hyprlock/foreground.png
    zindex = 4
}
# # INPUT FIELD
#
# # input-field {
# #     monitor =
# #     size = 250, 50
# #     outline_thickness = 2
# #     dots_size = 0.1
# #     dots_spacing = 0.3
# #     outer_color = rgba(908F9F55)
# #   inner_color = rgba(33333311)
# #   font_color = rgba(C6C5D6FF)
# #   # fade_on_empty = true
#     position = 0, 20
#     halign = center
#     valign = center
# }

input-field {
    monitor =
    size = 11%, 5%
    outline_thickness = 2
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.35 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    # shadow_size = 10
    outer_color =  rgb(e687a4) rgb(d43565) 15deg
    fail_color=rgba(ff6633ee) rgba(ff0066ee) 40deg
    inner_color = rgba(255, 255, 255, 0.5)  
  font_color = rgb(0, 0, 0)
    check_color =  rgb(253, 198, 252);
    # border_size = 10
    fade_on_empty = true
    rounding = -1
    placeholder_text = <i><span font_family="DS Moster" foreground="##1e1e2e">Input Password...</span></i>
    hide_input = false
    position = -24, -400
    halign = center
    valign = center
  zindex = 5
}

# DATE
# label {
#   monitor =
#   text = cmd[update:1000] echo "$(date +"%A, %B %d")"
#   color = $entry_color
#   font_size = 22
#   font_family = Bebas Neue
#   position = 0, -400
#   halign = center
#   valign = center
# }
#
# TIME
label {
  monitor = 
  text = cmd[update:1000] echo "<i>$(date +"%-H")</i>"
  color = $entry_color 
  font_size = $clock_font_size
  font_family = DS Moster
  position = -292, 35
  halign = center
  valign = center
  zindex = 2
}

label {
  monitor = 
  text = cmd[update:1000] echo "<i>$(date +"%M")</i>"
  color = $entry_color 
  font_size = $clock_font_size
  font_family = DS Moster
  position = 120, 35
  halign = center
  valign = center
  zindex = 2
}



# Profile Picture
# image {
#     monitor =
#     path = ~/.config/hypr/aqua.jpg
#     size = 150
#     border_size = 1.2
#     border_color = $entry_color 
#     position = 0, -100
#     halign = center
#     valign = center
# }

# #
# Desktop Environment
# image {
#     monitor =
#     path = ~/.config/hypr/aqua.jpg
#     size = 75
#     border_size = 2
#     border_color =$entry_color 
#     position = -50, 50
#     halign = right
#     valign = bottom
#     zindex = 5
# }

# CURRENT SONG
label {
    monitor =
    text = cmd[update:1000] echo "$(playerctl metadata --format '{{artist}} - {{title}}' 2>/dev/null)" 
    color = $entry_color 
    font_size = 16
    font_family = DS Moster
    position = -20, 50
    halign = center
    valign = bottom
  zindex = 5
}

# label {
#     monitor =
#     text = cmd[update:1000] echo "$(whoami)"
#     color =  $entry_color 
#   font_size = 14
#     font_family = JetBrains Mono
#     position = 0, -10
#     halign = center
#     valign = top
# }
#
label {
    monitor =
    text = cmd[update:1000] echo "$(~/.config/scripts/battery_status.sh)"
    color = $entry_color 
    font_size = 17
    font_family = JetBrains Mono
    position = -50, -10
    halign = right
    valign = top
  zindex = 5
}

# label {
#     monitor =
#     text = cmd[update:1000] echo "$(/home/justin/Documents/Scripts/network-status.sh)"
#     color = #eba0ac
#     font_size = 24
#     font_family = JetBrains Mono
#     position = -20, -10
#     halign = right
#     valign = top
# }
